name: Build
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  osx:
    name: Build (${{ matrix.target.name }})
    runs-on: macos-15-intel
    strategy:
      matrix:
        target:
#         - name: osx-x64-debug
#           configuration: 'Debug'
#           build-args: ''
#           release-name: 'osx.x64.Debug'
#         - name: osx-arm64-debug
#           configuration: 'Debug'
#           build-args: ''
#           release-name: 'osx.arm64.Debug'
          - name: osx-x64
            configuration: 'Release'
            build-args: ''
            release-name: 'osx.x64.Release'
#          - name: osx-arm64
#            configuration: 'Release'
#            build-args: ''
#            release-name: 'osx.arm64.Release'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./build.sh clr -c ${{ matrix.target.configuration }} ${{ matrix.target.build-args }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.name }}
          path: |
            artifacts/bin/coreclr/${{ matrix.target.release-name }}/libcoreclr.dylib
            artifacts/bin/coreclr/${{ matrix.target.release-name }}/libclrjit.dylib
            artifacts/bin/coreclr/${{ matrix.target.release-name }}/System.Private.CoreLib.dll

  release:
    name: Create release
    if: github.ref_type == 'tag'
    needs: [ osx ]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Package
        run: |
          for dir in */; do
            zip "${dir%/}.zip" ${dir}*
          done

      - name: Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          files: '*.zip'
